### ISSUE TITLE
The consumer side of the relation holds the private key in state

### ISSUE THREAD

**Issue by grobbie** [canonical/manual-tls-certificates-operator#159]
#### Describe the bug
When running `juju show-unit traefik-k8s/0` on a traefik charm integrated with manual-tls-certificates-operator, I noticed that there's a field `private_key` on the `peers` relation which contains the private key material related to the CSR that the unit has outstanding. This seems like too much information to me - the private key shouldn't be on display like this in an unprotected form.

**Comment by gruyaume** [comment]
Hello @grobbie, I understand your concern but I do not see how it is related to the `manual TLS certificates` operator. The charm authors for `tls-certificates` requirers decide where to place their private keys. In other words, while this may be the case in Traefik, it doesn't **have** to be and it is especially not caused by the Manual TLS Certificates charm.
